### ISSUE TITLE
Final score of the game

### ISSUE THREAD

**Issue by dineshpinto** [dblackrun/pbpstats#29]
First of all, thank you for building this package, it is very helpful!

This is probably a very silly question, but how do I get the final score from a particular game_id. 

I can query the game boxscore, but that just returns a list of scores with a lot of additional detail.

Thank you!

**Comment by dblackrun** [comment]
To get the score for a particular game id use the team_items property of the boxscore data:
```
from pbpstats.client import Client

settings = {
    "Boxscore": {"source": "web", "data_provider": "stats_nba"},
}
client = Client(settings)
game = client.Game("0021900001")
for team_line_item in game.boxscore.team_items:
    print(f"{team_line_item['team_abbreviation']}: {team_line_item['pts']}")
```

To get the final scores for all games use the final games property:
```
from pbpstats.client import Client

settings = {
    "Games": {"source": "web", "data_provider": "data_nba"},
}
client = Client(settings)
season = client.Season("nba", "2019-20", "Regular Season")

for final_game in season.games.final_games:
    print(final_game)
```

**Comment by dineshpinto** [comment]
Thank you, this is exactly what I was looking for!
