### ISSUE TITLE
Clarification regarding location corresponding to event

### ISSUE THREAD

**Issue by gabrielfior** [dblackrun/pbpstats#3]
When working with Events (StatsPbpEvent), I am trying to get the shot location inside the court, as very well plotted [here](https://dblackrun.github.io/2018/09/03/pbp-shot-quality-model.html).

I tried querying one game and checking the min and max values of loc_x and loc_y, respectively, arriving at following values:

loc_x: [-234.0,238.0]
loc_y: [-16.0, 258.0]

What is the unit of those locations? I assume (based in [this](https://nbviewer.jupyter.org/github/dblackrun/nba/blob/master/pbpstats_shot_quality/data_cleaning.ipynb) notebook) that the location should be divided by 10 to get the value in feet.

It would also be great to map the location to area of the court (above the break, corner, etc). I would be happy to help if the feature is not yet available.

```python
import pandas as pd
from pbpstats.stats_game_data import StatsGameData

gameid = '0021900001'
game_data = StatsGameData(gameid)
#game_data.get_game_data()
# to ignore rebound event order
game_data.get_game_data(ignore_rebound_and_shot_order=True)

list_events=[]
for i in range(len(game_data.Periods)):
    period = game_data.Periods[i]
    for j in range(len(period.Events)):
        event = period.Events[j]
        list_events.append((event.etype, event.description, event.clock_time, event.loc_x, event.loc_y))

df = pd.DataFrame(list_events, columns=['etype','description','clock_time','locx','locy'])
print (df['locx'].min(),df['locx'].min())
```

**Comment by dblackrun** [comment]
Yeah the location divided by 10 gets the value in feet.

You can use `event.is_corner_3()` method to check for corner 3s and `event.is_3pt_shot() and not event.is_corner_3()` to check for above the break 3s.

There is also an `event.get_shot_distance()` method to get the distance from the net in feet. 

You can also use `event.get_shot_type()` to get the shot type (AtRim (0-4ft), ShortMidRange (4-14ft), LongMidRange (14ft - 3pt line), Corner3, Arc3)

**Comment by gabrielfior** [comment]
Thanks for the answer @dblackrun!
