### ISSUE TITLE
G League — showcase cup games are shown, but not regular season games

### ISSUE THREAD

**Issue by eugenern** [dblackrun/pbpstats#39]
http://www.pbpstats.com/games/gleague?Season=2021-22&SeasonType=All
https://gleague.nba.com/schedule/
Also, the scores for games are often slightly lower on pbp than on the gleague site — are certain possessions not counted?

**Comment by dblackrun** [comment]
I've stopped supporting G League stats on pbpstats.com because barely anyone looks at them and it is too much of a pain to manually fix all the issues with the play-by-play data. As for the scores, I suspect that is probably an issue with calculating points with their free throw rules.
