### ISSUE TITLE
TeamHasBackToBackPossessionsException when jump ball leads to steal awarded to winner of jump ball

### ISSUE THREAD

**Issue by vukrado** [dblackrun/pbpstats#43]
```
<class 'pbpstats.data_loader.stats_nba.possessions.loader.TeamHasBackToBackPossessionsException'> 
GameId: 0022101208,
Events: [
    <StatsTurnover GameId: 0022101208, Description: Brown Jr. STEAL (1 STL): Harrell Lost Ball Turnover (P1.T7), Time: 11:24, EventNum: 428>
],
Previous Events: [
    <StatsJumpBall GameId: 0022101208, Description: Jump Ball Brown Jr. vs. Harrell: Tip to Dosunmu, Time: 11:26, EventNum: 425>
]>
```

`TeamHasBackToBackPossessionsException` occurs when a steal is awarded to the winner of a jump ball, along with a turnover to the loser, these appear after the jump ball event, would manually putting the steal/turnover events prior to the jump ball stop this from being raised, I am also curious if it should be raised in the first place in these scenarios, as this seems like a valid scenario.

Thanks!

**Comment by dblackrun** [comment]
To get around this you need to manually edit the time to be the same for the jump ball and steal events. So in this case changing the steal time to 11:26 should fix it.

**Comment by vukrado** [comment]
Thanks!
